server:
  port: 9092
  servlet:
    context-path: /wx
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB
  tomcat:
    max-connections: 10
    accept-count: 100
    threads:
      max: 200

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.26.134:3306/fm_hospital?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=false
      username: root
      password: root
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: 192.168.26.134
    port: 6379
    password: admin123
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  quartz:
    job-store-type: memory

  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: token
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hospital.hms.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.hospital.hms.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on
minio:
  endpoint: http://192.168.26.134:9000
  access-key: root
  secret-key: root123456
  bucket-name: hospital
  base-url: http://192.168.26.134:9000/hospital
wechat:
  app-id: wxe57c93bba08fcb97
  app-secret: 5601444e60eee46c903c654e394bd295
  pay:
    v3:
      patient-wx-api:
        app-id: wxe57c93bba08fcb97
        app-v3-secret: 5601444e60eee46c903c654e394bd295
        mch-id: 微信企业商户平台ID
        domain: http://内网穿透的外网IP地址和端口/patient-wx-api
        cert-path: apiclient_cert.p12

tencent:
  cloud:
    appId: wxe57c93bba08fcb97
    secretId: AKIDWzGLDsKkS5Xt32nKgojRwGNGwQmxudBV
    secretKey: DDzYv53oRsJguvoeNvHSQDnALJPJzUnt
    face:
      groupName: yiliao
      region: ap-guangzhou
  trtc:
    appId: xxx
    secretKey: xxx
    expire: 86400